### PR TITLE
5pm d add sections days and times

### LINKED ISSUE #37: Add the lecture section days and times
# User Story

As a user I can see the lecture day and time when searching so that I know when the class starts.

# Acceptance Criteria

- [x] Every class lecture day and time shows up.
- [x] Courses that don't have a specified day and time should still work properly.

# Implementation Todos

Front end:

- [x] Modify the proper component to display the lecture day and time.

Back end:

- No changes needed

Testing:

- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by andrewberry391**
This PR closes #37. This adds lectures and sections days and times to the table.

This animated gif shows before and after:

course-search-pr-77

### CODE REVIEW

**Review by pconrad — APPROVED** [review]
LGTM!  I'm just testing by deploying before merging

**Comment by pconrad** [comment]
Really nice job!   40 points

**Review by aezhao065 — APPROVED** [review]

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
Really nice job!   40 pts

**Pull request merged**
