### PR TITLE
5pm-a-course-search-by-name-code-cleanup

### PR DESCRIPTION
**Pull request by KobeShav**
ks - Removed unnecessary comments and white space.
Fixed ordering of quarters in CourseSearchCourseStartEndQtr to be in reverse chronological order
(i.e. Winter -> Spring -> Fall -> Summer -> Winter, from bottom to top)

### CODE REVIEW

**Review by kevbbn — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Review by andrewhlu — APPROVED** [review]
Still getting some weird course table bugs , but I think that's beyond the scope of this cleanup PR. Thanks for addressing my changes!

Bug is visible [here](https://ucsb-cs156-f20.slack.com/files/U01A470RH0X/F01GD6Q5SQN/2020-12-09_22-57-11.mp4) (this is a link to Slack since my GIF was too big and GitHub doesn't allow videos)

**Comment by pconrad** [comment]
10 point for this clean up pr

**Pull request merged**
