### PR TITLE
5pm b create menu item personal schedule

### PR DESCRIPTION
**Pull request by Icarus99**
Added a menu item called "personal schedule" in the Navbar

### CODE REVIEW

**Review by yiweizhangcs — DISMISSED** [review]
All good.

**Review by Mitchell57 — APPROVED** [review]
Looks good!

**Review by yiweizhangcs — DISMISSED** [review]

**Review by Mitchell57 — APPROVED** [review]
outdated but works

**Review by yiweizhangcs — APPROVED** [review]
make sense

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
20 points (probably 10, but I'm being generous :-) )

**Pull request merged**
